export const NAVIGATION_DRAWER_TOGGLE = 'NAVIGATION_DRAWER_TOGGLE'
export const BALANCE_GET_REQUEST = 'BALANCE_GET_REQUEST'
export const BALANCE_GET_SUCCESS = 'BALANCE_GET_SUCCESS'
export const BALANCE_GET_FAILURE = 'BALANCE_GET_FAILURE' 